/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2026-04-22 21:00:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class payments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1761663066000L));
    _jspx_dependants.put("jar:file:/C:/Users/adonis/Documents/Projects/Lottery/deploy/apache-tomcat-10.1.28/webapps/Lottery/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Fortuna Lotto - Payment Methods</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/variables.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/lottery-style.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/userShared.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/payments.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Poppins:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body class=\"dashboard-page\">\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/fragments/userHeader.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Payment Methods", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"content-wrapper\">\n");
      out.write("            <div class=\"main-content\">\n");
      out.write("                <div class=\"sidebar\">\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/fragments/sidebar.jsp", out, false);
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"container\">\n");
      out.write("                ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /payments.jsp(29,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.message}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    <div class=\"message ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.messageType}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("                    ");
 session.removeAttribute("message"); 
            out.write("\n");
            out.write("                    ");
 session.removeAttribute("messageType"); 
            out.write("\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\n");
      out.write("                \n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h2>Add New Payment Method</h2>\n");
      out.write("                    <form id=\"paymentForm\" method=\"post\" action=\"payments\">\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"addPayment\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"cardNumber\">Card Number</label>\n");
      out.write("                            <input type=\"text\" id=\"cardNumber\" name=\"cardNumber\" placeholder=\"Enter card number\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"cardHolder\">Card Holder Name</label>\n");
      out.write("                            <input type=\"text\" id=\"cardHolder\" name=\"cardHolder\" placeholder=\"Enter card holder name\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"expiryMonth\">Expiry Date</label>\n");
      out.write("                            <div style=\"display: flex; gap: 10px;\">\n");
      out.write("                                <input type=\"text\" id=\"expiryMonth\" name=\"expiryMonth\" placeholder=\"MM\" required style=\"flex: 1;\">\n");
      out.write("                                <input type=\"text\" id=\"expiryYear\" name=\"expiryYear\" placeholder=\"YY\" required style=\"flex: 1;\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"cvv\">CVV</label>\n");
      out.write("                            <input type=\"text\" id=\"cvv\" name=\"cvv\" placeholder=\"CVV\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <button type=\"submit\" class=\"btn lottery-btn\">Add Payment Method</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        document.getElementById('paymentForm').addEventListener('submit', function(e) {\n");
      out.write("            \n");
      out.write("            const cardNumber = document.getElementById('cardNumber');\n");
      out.write("            const cardHolder = document.getElementById('cardHolder');\n");
      out.write("            const expiryMonth = document.getElementById('expiryMonth');\n");
      out.write("            const expiryYear = document.getElementById('expiryYear');\n");
      out.write("            const cvv = document.getElementById('cvv');\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            clearErrors();\n");
      out.write("            \n");
      out.write("            let hasErrors = false;\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (!cardNumber.value || cardNumber.value.trim() === '') {\n");
      out.write("                showError(cardNumber, 'Card number is required.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            } else if (!luhnCheck(cardNumber.value.replace(/\\s+/g, ''))) {\n");
      out.write("                showError(cardNumber, 'Invalid card number. Please check your card details.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (!cardHolder.value || cardHolder.value.trim() === '') {\n");
      out.write("                showError(cardHolder, 'Card holder name is required.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (!expiryMonth.value || expiryMonth.value.trim() === '') {\n");
      out.write("                showError(expiryMonth, 'Expiry month is required.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            } else if (!/^\\d{2}$/.test(expiryMonth.value) || parseInt(expiryMonth.value) < 1 || parseInt(expiryMonth.value) > 12) {\n");
      out.write("                showError(expiryMonth, 'Invalid expiry month. Use MM format (01-12).');\n");
      out.write("                hasErrors = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (!expiryYear.value || expiryYear.value.trim() === '') {\n");
      out.write("                showError(expiryYear, 'Expiry year is required.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            } else if (!/^\\d{2}$/.test(expiryYear.value)) {\n");
      out.write("                showError(expiryYear, 'Invalid expiry year. Use YY format.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (!cvv.value || cvv.value.trim() === '') {\n");
      out.write("                showError(cvv, 'CVV is required.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            } else if (!/^\\d{3,4}$/.test(cvv.value)) {\n");
      out.write("                showError(cvv, 'Invalid CVV. Must be 3 or 4 digits.');\n");
      out.write("                hasErrors = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            if (hasErrors) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        function showError(element, message) {\n");
      out.write("            \n");
      out.write("            let errorElement = element.parentNode.querySelector('.error-message');\n");
      out.write("            if (!errorElement) {\n");
      out.write("                errorElement = document.createElement('div');\n");
      out.write("                errorElement.className = 'error-message';\n");
      out.write("                errorElement.style.color = '#dc3545';\n");
      out.write("                errorElement.style.fontSize = '12px';\n");
      out.write("                errorElement.style.marginTop = '5px';\n");
      out.write("                element.parentNode.appendChild(errorElement);\n");
      out.write("            }\n");
      out.write("            errorElement.textContent = message;\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            element.style.borderColor = '#dc3545';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function clearErrors() {\n");
      out.write("            \n");
      out.write("            const errorElements = document.querySelectorAll('.error-message');\n");
      out.write("            errorElements.forEach(element => element.remove());\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            const inputs = document.querySelectorAll('#paymentForm input');\n");
      out.write("            inputs.forEach(input => input.style.borderColor = '#3a3f5a');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function luhnCheck(cardNumber) {\n");
      out.write("            let sum = 0;\n");
      out.write("            let isEven = false;\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            for (let i = cardNumber.length - 1; i >= 0; i--) {\n");
      out.write("                let digit = parseInt(cardNumber.charAt(i), 10);\n");
      out.write("                \n");
      out.write("                if (isEven) {\n");
      out.write("                    digit *= 2;\n");
      out.write("                    if (digit > 9) {\n");
      out.write("                        digit -= 9;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                sum += digit;\n");
      out.write("                isEven = !isEven;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            return sum % 10 === 0;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /payments.jsp(62,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty paymentMethods}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <div class=\"card\">\n");
          out.write("                        <h2>Your Payment Methods</h2>\n");
          out.write("                        <table class=\"ticket-table\">\n");
          out.write("                            <thead>\n");
          out.write("                                <tr>\n");
          out.write("                                    <th>Card Number</th>\n");
          out.write("                                    <th>Card Holder</th>\n");
          out.write("                                    <th>Expiry Date</th>\n");
          out.write("                                    <th>Action</th>\n");
          out.write("                                </tr>\n");
          out.write("                            </thead>\n");
          out.write("                            <tbody>\n");
          out.write("                                ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                            </tbody>\n");
          out.write("                        </table>\n");
          out.write("                    </div>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /payments.jsp(75,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("payment");
      // /payments.jsp(75,32) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/payments.jsp(75,32) '${paymentMethods}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${paymentMethods}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                    <tr>\n");
            out.write("                                        <td data-label=\"Card Number\">**** **** **** ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.lastFourDigits}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                        <td data-label=\"Card Holder\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.cardHolder}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                        <td data-label=\"Expiry Date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.expiryDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                        <td data-label=\"Action\">\n");
            out.write("                                            <form method=\"post\" action=\"payments\" style=\"display: inline;\">\n");
            out.write("                                                <input type=\"hidden\" name=\"action\" value=\"deletePayment\">\n");
            out.write("                                                <input type=\"hidden\" name=\"paymentId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                                                <button type=\"submit\" class=\"btn lottery-btn\" onclick=\"return confirm('Are you sure you want to delete this payment method?')\">Delete</button>\n");
            out.write("                                            </form>\n");
            out.write("                                        </td>\n");
            out.write("                                    </tr>\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
