/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2026-04-22 21:00:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.lottery.model.User;
import jakarta.servlet.http.HttpSession;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1761663066000L));
    _jspx_dependants.put("jar:file:/C:/Users/adonis/Documents/Projects/Lottery/deploy/apache-tomcat-10.1.28/webapps/Lottery/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("com.lottery.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    
    if (request.getAttribute("user") == null && session.getAttribute("user") != null) {
        request.setAttribute("user", session.getAttribute("user"));
    }
    
    User user = (User) session.getAttribute("user");
    String successMessage = (String) session.getAttribute("successMessage");
    String errorMessage = (String) session.getAttribute("errorMessage");
    String pendingEmail = (String) session.getAttribute("pendingEmail");
    
    
    if (successMessage != null) session.removeAttribute("successMessage");
    if (errorMessage != null) session.removeAttribute("errorMessage");
    
    String displayName = (user != null && user.getDisplayName() != null) ? user.getDisplayName() :
                        (user != null ? user.getFirstName() + " " + user.getLastName() : "");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>My Profile - Lottery</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/variables.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/lottery-style.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/userShared.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/userLottery.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/profile.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Poppins:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css?v=");
      out.print( System.currentTimeMillis() );
      out.write("\">\n");
      out.write("</head>\n");
      out.write("<body class=\"dashboard-page\">\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/fragments/userHeader.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("My Profile", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"content-wrapper\">\n");
      out.write("            <div class=\"main-content\">\n");
      out.write("                <div class=\"sidebar\">\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/fragments/sidebar.jsp", out, false);
      out.write("\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"profile-container\">\n");
      out.write("                        \n");
      out.write("                        ");
 if (successMessage != null) { 
      out.write("\n");
      out.write("                            <div class=\"message success\">");
      out.print( successMessage );
      out.write("</div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        \n");
      out.write("                        ");
 if (errorMessage != null) { 
      out.write("\n");
      out.write("                            <div class=\"message error\">");
      out.print( errorMessage );
      out.write("</div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("                        <div class=\"profile-section\">\n");
      out.write("                            <h2>Name</h2>\n");
      out.write("                            <form action=\"profile\" method=\"post\">\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"updateName\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"firstName\">First Name</label>\n");
      out.write("                                    <input type=\"text\" id=\"firstName\" name=\"firstName\" \n");
      out.write("                                           value=\"");
      out.print( user != null && user.getFirstName() != null ? user.getFirstName() : "" );
      out.write("\" maxlength=\"50\" required>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"lastName\">Last Name</label>\n");
      out.write("                                    <input type=\"text\" id=\"lastName\" name=\"lastName\" \n");
      out.write("                                           value=\"");
      out.print( user != null && user.getLastName() != null ? user.getLastName() : "" );
      out.write("\" maxlength=\"50\" required>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn\">Update Name</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("                        <div class=\"profile-section\">\n");
      out.write("                            <h2>Email Address</h2>\n");
      out.write("                            <p>Current email: <strong>");
      out.print( user != null && user.getEmail() != null && !user.getEmail().isEmpty() 
                                ? user.getEmail() 
                                : "No email set (logged in via Google)" );
      out.write("</strong></p>\n");
      out.write("                            \n");
      out.write("                            <form action=\"profile\" method=\"post\">\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"requestEmailChange\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"newEmail\">New Email Address</label>\n");
      out.write("                                    <input type=\"email\" id=\"newEmail\" name=\"newEmail\" required>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn\">Send Verification Code</button>\n");
      out.write("                            </form>\n");
      out.write("                            \n");
      out.write("                            ");
 if (pendingEmail != null) { 
      out.write("\n");
      out.write("                            <div class=\"verification-section\">\n");
      out.write("                                <p>A verification code was sent to <strong>");
      out.print( pendingEmail );
      out.write("</strong></p>\n");
      out.write("                                <form action=\"profile\" method=\"post\">\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"verifyEmailCode\">\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label for=\"verificationCode\">Verification Code</label>\n");
      out.write("                                        <input type=\"text\" id=\"verificationCode\" name=\"verificationCode\" \n");
      out.write("                                               placeholder=\"Enter 6-digit code\" maxlength=\"6\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <button type=\"submit\" class=\"btn\">Verify & Update Email</button>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("                        <div class=\"profile-section\">\n");
      out.write("                            <h2>Change Password</h2>\n");
      out.write("                            <form action=\"profile\" method=\"post\">\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"changePassword\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"currentPassword\">Current Password</label>\n");
      out.write("                                    <input type=\"password\" id=\"currentPassword\" name=\"currentPassword\" required>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"newPassword\">New Password</label>\n");
      out.write("                                    <input type=\"password\" id=\"newPassword\" name=\"newPassword\" required>\n");
      out.write("                                    <p class=\"password-hint\">Min 8 characters. Must include: uppercase, lowercase, number, and special character (!@#$%^&* etc).</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <label for=\"confirmPassword\">Confirm New Password</label>\n");
      out.write("                                    <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn\">Change Password</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
