
google.client.id=983186456814-h0gbid9h86576smkg6k89h4ll5jj8vae.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/Lottery/oauth/google/callback