/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2026-04-21 23:58:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.fragments;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adminSidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1761663066000L));
    _jspx_dependants.put("jar:file:/C:/Users/adonis/Documents/Projects/Lottery/deploy/apache-tomcat-10.1.28/webapps/Lottery/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2><i class=\"fas fa-user-shield\"></i> Admin Dashboard</h2>\n");
      out.write("<ul>\n");
      out.write("    <li><a href=\"userManagement\"><i class=\"fas fa-users\"></i> User Management</a></li>\n");
      out.write("    <li><a href=\"paymentMethodManagement\"><i class=\"fas fa-credit-card\"></i> Payment Methods</a></li>\n");
      out.write("    <li><a href=\"adminLottery\"><i class=\"fas fa-ticket-alt\"></i> Lottery Management</a></li>\n");
      out.write("    <li><a href=\"adminTransactions\"><i class=\"fas fa-exchange-alt\"></i> Transactions Management</a></li>\n");
      out.write("    <li><a href=\"adminProfile\"><i class=\"fas fa-user\"></i> My Profile</a></li>\n");
      out.write("    <li class=\"logout-item\" style=\"margin-top: 30px;\"><a href=\"logout\" style=\"color: #ff5252;\"><i class=\"fas fa-sign-out-alt\"></i> Logout</a></li>\n");
      out.write("</ul>\n");
      out.write("<script>\n");
      out.write("    \n");
      out.write("    (function() {\n");
      out.write("        if (document.getElementById('mobile-sidebar-init')) return;\n");
      out.write("        var marker = document.createElement('meta');\n");
      out.write("        marker.id = 'mobile-sidebar-init';\n");
      out.write("        document.head.appendChild(marker);\n");
      out.write("\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            var sidebar = document.querySelector('.sidebar');\n");
      out.write("            if (!sidebar) return;\n");
      out.write("\n");
      out.write("            var isMobile = function() { return window.innerWidth <= 768; };\n");
      out.write("            var sidebarOpen = false;\n");
      out.write("            function setImp(p, v) { sidebar.style.setProperty(p, v, 'important'); }\n");
      out.write("            \n");
      out.write("            function applyMobileStyles() {\n");
      out.write("                if (isMobile()) {\n");
      out.write("                    setImp('position', 'fixed');\n");
      out.write("                    setImp('top', '0');\n");
      out.write("                    setImp('left', sidebarOpen ? '0' : '-280px');\n");
      out.write("                    setImp('width', '260px');\n");
      out.write("                    setImp('height', '100vh');\n");
      out.write("                    setImp('z-index', '9999');\n");
      out.write("                    setImp('background-color', '#1a1a2e');\n");
      out.write("                    setImp('border-right', '1px solid #3a3f5a');\n");
      out.write("                    setImp('padding', '20px');\n");
      out.write("                    setImp('transition', 'left 0.3s ease');\n");
      out.write("                    setImp('overflow-y', 'auto');\n");
      out.write("                    setImp('flex-shrink', 'unset');\n");
      out.write("                    if (sidebarOpen) {\n");
      out.write("                        setImp('box-shadow', '5px 0 25px rgba(0,0,0,0.5)');\n");
      out.write("                    } else {\n");
      out.write("                        setImp('box-shadow', 'none');\n");
      out.write("                    }\n");
      out.write("                    closeBtn.style.setProperty('display', 'flex', 'important');\n");
      out.write("                    toggle.style.setProperty('display', 'flex', 'important');\n");
      out.write("                } else {\n");
      out.write("                    \n");
      out.write("                    var props = ['position', 'top', 'left', 'width', 'height', 'z-index', 'background-color', 'border-right', 'padding', 'transition', 'overflow-y', 'flex-shrink', 'box-shadow'];\n");
      out.write("                    props.forEach(function(p) { sidebar.style.removeProperty(p); });\n");
      out.write("                    closeBtn.style.setProperty('display', 'none', 'important');\n");
      out.write("                    toggle.style.setProperty('display', 'none', 'important');\n");
      out.write("                    sidebarOpen = false;\n");
      out.write("                    backdrop.classList.remove('active');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            \n");
      out.write("            var closeBtn = document.createElement('button');\n");
      out.write("            closeBtn.setAttribute('data-mobile-nav', 'true');\n");
      out.write("            closeBtn.innerHTML = '&times;';\n");
      out.write("            closeBtn.style.cssText = 'display:none;position:absolute;top:10px;right:10px;width:32px;height:32px;background:transparent;border:1px solid #3a3f5a;border-radius:6px;color:#ff5252;font-size:18px;cursor:pointer;align-items:center;justify-content:center;z-index:10000;padding:0;';\n");
      out.write("            closeBtn.addEventListener('click', function(e) {\n");
      out.write("                e.stopPropagation();\n");
      out.write("                closeSidebar();\n");
      out.write("            });\n");
      out.write("            sidebar.insertBefore(closeBtn, sidebar.firstChild);\n");
      out.write("\n");
      out.write("            \n");
      out.write("            var backdrop = document.createElement('div');\n");
      out.write("            backdrop.className = 'mobile-sidebar-backdrop';\n");
      out.write("            backdrop.addEventListener('click', closeSidebar);\n");
      out.write("            document.body.appendChild(backdrop);\n");
      out.write("\n");
      out.write("            \n");
      out.write("            var toggle = document.createElement('button');\n");
      out.write("            toggle.className = 'mobile-menu-toggle';\n");
      out.write("            toggle.setAttribute('data-mobile-nav', 'true');\n");
      out.write("            toggle.innerHTML = '<i class=\"fas fa-bars\"></i>';\n");
      out.write("            toggle.addEventListener('click', function(e) {\n");
      out.write("                e.stopPropagation();\n");
      out.write("                openSidebar();\n");
      out.write("            });\n");
      out.write("            var header = document.querySelector('.header');\n");
      out.write("            if (header) {\n");
      out.write("                header.insertBefore(toggle, header.firstChild);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function openSidebar() {\n");
      out.write("                sidebarOpen = true;\n");
      out.write("                sidebar.style.setProperty('left', '0', 'important');\n");
      out.write("                sidebar.style.setProperty('box-shadow', '5px 0 25px rgba(0,0,0,0.5)', 'important');\n");
      out.write("                sidebar.classList.add('mobile-open');\n");
      out.write("                backdrop.classList.add('active');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function closeSidebar() {\n");
      out.write("                sidebarOpen = false;\n");
      out.write("                sidebar.style.setProperty('left', '-280px', 'important');\n");
      out.write("                sidebar.style.setProperty('box-shadow', 'none', 'important');\n");
      out.write("                sidebar.classList.remove('mobile-open');\n");
      out.write("                backdrop.classList.remove('active');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            \n");
      out.write("            setTimeout(function() {\n");
      out.write("                var mobileNavBtns = document.querySelectorAll('[data-mobile-nav]');\n");
      out.write("                mobileNavBtns.forEach(function(btn) {\n");
      out.write("                    btn.classList.remove('lottery-btn');\n");
      out.write("                });\n");
      out.write("            }, 200);\n");
      out.write("\n");
      out.write("            \n");
      out.write("            applyMobileStyles();\n");
      out.write("            window.addEventListener('resize', applyMobileStyles);\n");
      out.write("        });\n");
      out.write("    })();\n");
      out.write("</script>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
